#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f &
pgrep -x dunst > /dev/null || dunst &
pgrep -x flameshot > /dev/null || flameshot &
setxkbmap -option "ctrl:swapcaps" &
xcape -e Control_L=Escape -t 200  &
xset r rate 300 50  &


#if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
xrandr --output eDP1 --mode 1366x768 --pos 0x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 1366x0 --rotate normal --output DP1 --off
#xrandr --output eDP-1 --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --pos 1366x0 --rotate normal --output DP-1 --off
xrandr --output HDMI-1 --set TearFree on
fi

$HOME/.config/polybar/launch.sh
feh --bg-scale --randomize /home/pawan/test/images/* &


# bspc monitor -d I II III IV V VI VII VIII IX X 
bspc monitor HDMI1 -d 6 7 8 9 0 
bspc monitor eDP1 -d 1 2 3 4 5  

bspc config border_width         1
bspc config window_gap           3
bspc config focused_border_color "#FFFFFF"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^0'
bspc rule -a Skype desktop='^2'
bspc rule -a Mattermost desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
