#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
xrandr --output eDP-1 --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --pos 1366x0 --rotate normal --output DP-1 --off
fi

$HOME/.config/polybar/launch.sh

# bspc monitor -d I II III IV V VI VII VIII IX X 
bspc monitor HDMI-1 -d 1 2 3 4 5 6 
bspc monitor eDP-1 -d  0 

bspc config border_width         1
bspc config window_gap           1
bspc config focused_border_color "#5381ac"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^0'
bspc rule -a Mattermost desktop='^3'
bspc rule -a Skype desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
